version: "3.7"
services:
  rabbitmq3:
      container_name: "rabbitmq"
      image: rabbitmq:3.8-management
      environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
      ports:
          # AMQP protocol port
          - '5672:5672'
          # HTTP management UI
          - '15672:15672'
      volumes:
          - ./db-data:/var/lib/rabbitmq
  mysql:
    container_name: "mdsdb"
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./test-sql-2:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql